import ResponsiveImage from './ResponsiveImage';
import {useEffect,useState} from 'react';
import VideoPlayer from './VideoPlayer';
import MediaDialog from './MediaDialog';
import {safeHref} from '../lib/pageContent';
import {ChevronLeft,ChevronRight,Play,X} from 'lucide-react';

function youtubePoster(url){try{const parsed=new URL(url);const id=parsed.hostname==='youtu.be'?parsed.pathname.slice(1):parsed.pathname.startsWith('/shorts/')||parsed.pathname.startsWith('/embed/')?parsed.pathname.split('/')[2]:parsed.searchParams.get('v');return /^[\w-]{11}$/.test(id||'')?`https://img.youtube.com/vi/${id}/hqdefault.jpg`:'';}catch{return '';}}
export default function PartnerMediaShowcase({media={},name}){
 const videos=(Array.isArray(media?.videos)?media.videos:[]).filter(Boolean),images=(Array.isArray(media?.gallery_images)?media.gallery_images:[]).filter(Boolean);
 const [open,setOpen]=useState(null);
 useEffect(()=>{if(!open)return;const key=e=>{if(e.key==='ArrowRight')setOpen(o=>({...o,index:(o.index+1)%(o.kind==='film'?videos.length:images.length)}));if(e.key==='ArrowLeft')setOpen(o=>({...o,index:(o.index-1+(o.kind==='film'?videos.length:images.length))%(o.kind==='film'?videos.length:images.length)}));};window.addEventListener('keydown',key);return()=>{window.removeEventListener('keydown',key);};},[open,videos.length,images.length]);
 if(!videos.length&&!images.length)return null;
 const list=open?.kind==='film'?videos:images;
 const change=delta=>setOpen(o=>({...o,index:(o.index+delta+list.length)%list.length}));
 return <section className="partner-media-showcase" aria-label={`${name} media`}>
 {videos.length>0&&<div><div className="partner-media-heading"><h2>Films & walkthroughs</h2><span>{videos.length} film{videos.length===1?'':'s'} · Select to play</span></div><div className="partner-media-strip">{videos.map((src,i)=>{const title=(media.video_titles?.[i]||'').trim()||`Film ${String(i+1).padStart(2,'0')}`;return <button type="button" key={`${src}-${i}`} className="partner-media-thumb" onClick={()=>setOpen({kind:'film',index:i})} aria-label={`Play ${title}`}><div className="partner-media-image">{safeHref(media.video_posters?.[i])||youtubePoster(src)?<ResponsiveImage src={safeHref(media.video_posters?.[i])||youtubePoster(src)} alt="" loading="lazy"/>:<div className="partner-media-placeholder">{title}</div>}<span className="partner-media-play"><Play size={20} fill="currentColor"/></span></div><strong title={title}>{title}</strong></button>;})}</div></div>}
 {images.length>0&&<div><div className="partner-media-heading"><h2>Selected work</h2><span>{images.length} image{images.length===1?'':'s'} · Select to explore</span></div><div className="partner-media-strip" data-testid="partner-gallery">{images.map((src,i)=>{const title=(media.gallery_captions?.[i]||'').trim()||`Image ${String(i+1).padStart(2,'0')}`;return <button type="button" key={`${src}-${i}`} className="partner-media-thumb" onClick={()=>setOpen({kind:'image',index:i})} aria-label={`View ${title}`}><div className="partner-media-image"><ResponsiveImage src={safeHref(src)} alt={title} loading="lazy"/></div><strong title={title}>{title}</strong></button>;})}</div></div>}
 {open&&<MediaDialog className="partner-media-modal" onClose={()=>setOpen(null)} label={`${open.kind==='film'?(media.video_titles?.[open.index]||'Film'):(media.gallery_captions?.[open.index]||'Image')} ${open.index+1} of ${list.length}`}><div className="partner-media-modal-inner"><div className="partner-media-modal-bar"><span>{open.kind==='film'?(media.video_titles?.[open.index]||`Film ${open.index+1}`):(media.gallery_captions?.[open.index]||`Image ${open.index+1}`)}</span><button type="button" onClick={()=>setOpen(null)} aria-label="Close media"><X/></button></div>{open.kind==='film'?<VideoPlayer autoPlay key={`${open.index}-${list[open.index]}`} src={list[open.index]} poster={safeHref(media.video_posters?.[open.index])||youtubePoster(list[open.index])} title={`${name}: ${media.video_titles?.[open.index]||`Film ${open.index+1}`}`} className="aspect-video"/>:<ResponsiveImage className="partner-media-modal-image" key={list[open.index]} src={safeHref(list[open.index])} alt={media.gallery_captions?.[open.index]||`${name} gallery image ${open.index+1}`}/>}{list.length>1&&<div className="partner-media-modal-nav"><button type="button" onClick={()=>change(-1)} aria-label="Previous"><ChevronLeft/> Previous</button><button type="button" onClick={()=>change(1)} aria-label="Next">Next <ChevronRight/></button></div>}</div></MediaDialog>}
 </section>;
}
