import {useState} from 'react';
import axios from 'axios';
import {API,auth,errorMessage} from '../../lib/cms';
import {Field} from './Fields';
export default function LeadDetails({lead,token,onClose,onSaved}){
 const [form,setForm]=useState({...lead}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const action=async fn=>{setBusy(true);setError('');try{await fn();onSaved();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}};
 return <div className="fixed inset-0 bg-black/50 z-50 p-4 flex items-center justify-center"><section role="dialog" aria-modal="true" aria-label="Enquiry details" className="bg-white max-w-2xl w-full max-h-[90vh] overflow-auto p-6 space-y-5"><div className="flex justify-between"><h2 className="text-2xl">{lead.name}</h2><button onClick={onClose}>Close</button></div><p>{lead.phone} · {lead.email}</p><p className="whitespace-pre-wrap border p-4">{lead.message||'No message supplied'}</p><dl className="text-sm grid grid-cols-2 gap-3">{['enquiry_type','project_type','project_location','budget_range','timeline','partner_ref','leader_ref','project_ref','service_ref','landing_page','submission_page','utm_source','utm_medium','utm_campaign'].filter(k=>lead[k]).map(k=><div key={k}><dt className="text-neutral-500">{k.replaceAll('_',' ')}</dt><dd className="break-words">{lead[k]}</dd></div>)}</dl><form className="space-y-4" onSubmit={e=>{e.preventDefault();action(async()=>{await axios.patch(`${API}/leads/${lead.id}`,{status:form.status,owner:form.owner||'',notes:form.notes||'',next_action:form.next_action||'',follow_up_at:form.follow_up_at||''},auth(token));onClose();});}}><Field label="Status"><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{['new','contacted','qualified','closed','archived'].map(s=><option key={s}>{s}</option>)}</select></Field>{['owner','next_action','notes'].map(k=><Field key={k} label={k.replaceAll('_',' ')}><textarea rows={k==='notes'?4:1} value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})}/></Field>)}<Field label="Follow up (UTC)"><input type="datetime-local" value={form.follow_up_at?.slice(0,16)||''} onChange={e=>setForm({...form,follow_up_at:e.target.value?e.target.value+':00+00:00':''})}/></Field><button disabled={busy} className="bg-black text-white px-5 py-3">Save follow-up</button></form><p>Email notification: {lead.notification_status||'Unknown'}</p>{lead.notification_status==='failed'&&<button disabled={busy} onClick={()=>action(()=>axios.post(`${API}/leads/${lead.id}/retry-notification`,{},auth(token)))}>Retry notification</button>}{error&&<p role="alert" className="text-red-700">{error}</p>}</section></div>;
}
