import { useEffect, useState } from 'react';
import axios from 'axios';
import { API, auth, bl, errorMessage } from '../../lib/cms';
import { Field, BilingualField, PublicationFields, SEOFields } from './Fields';
import { uploadFile } from '../../hooks/useApi';
const blank = () => ({slug:'',name:bl(),title:bl(),bio:bl(),photo:'',hierarchy_rank:100,expertise:[],qualifications:[],status:'draft',publication_reviewed:false,seo:{}});
export default function LeadersTab({token}) {
  const [items,setItems]=useState([]), [form,setForm]=useState(null), [editing,setEditing]=useState(false), [error,setError]=useState(''), [busy,setBusy]=useState(false);
  const refresh=()=>axios.get(`${API}/leaders?published_only=false`,auth(token)).then(r=>setItems(r.data)).catch(e=>setError(errorMessage(e)));
  useEffect(()=>{refresh();},[token]); // eslint-disable-line react-hooks/exhaustive-deps
  const save=async e=>{e.preventDefault();setBusy(true);setError('');try{await axios[editing?'put':'post'](`${API}/leaders${editing?'/'+form.slug:''}`,form,auth(token));setForm(null);await refresh();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}};
  return <section className="bg-white p-6 space-y-6"><div className="flex justify-between"><h2 className="text-xl">Project leaders</h2><button onClick={()=>{setForm(blank());setEditing(false);}}>Add leader</button></div><p>Publish verified biographies, then credit people by their contribution to each project.</p>{error&&<p role="alert" className="text-red-700">{error}</p>}
    {form?<form onSubmit={save} className="space-y-5"><Field label="URL slug"><input required pattern="[a-z0-9]+(-[a-z0-9]+)*" disabled={editing} value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/></Field>{['name','title','bio'].map(k=><BilingualField key={k} label={k} value={form[k]} onChange={v=>setForm({...form,[k]:v})}/>)}<Field label="Hierarchy order (0 = first, 100 = default)"><input type="number" min="0" max="999" value={form.hierarchy_rank??100} onChange={e=>setForm({...form,hierarchy_rank:Number(e.target.value)})}/></Field><Field label="Portrait URL"><input value={form.photo||''} onChange={e=>setForm({...form,photo:e.target.value})}/></Field><Field label="Upload an approved portrait"><input type="file" accept="image/*" disabled={busy} onChange={async e=>{const file=e.target.files[0];if(!file)return;setBusy(true);try{const r=await uploadFile(token,file);setForm(f=>({...f,photo:r.url}));}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}}/></Field>{['expertise','qualifications'].map(k=><Field key={k} label={`${k} (one per line)`}><textarea value={form[k].join('\n')} onChange={e=>setForm({...form,[k]:e.target.value.split('\n')})}/></Field>)}<PublicationFields form={form} setForm={setForm}/><SEOFields value={form.seo} onChange={seo=>setForm({...form,seo})}/><div className="flex gap-4"><button disabled={busy} className="bg-black text-white p-3">Save leader</button><button type="button" onClick={()=>setForm(null)}>Cancel</button>{editing&&<a href={`/project-leaders/${form.slug}?preview=true`} target="_blank" rel="noreferrer">Preview</a>}</div></form>:<div className="divide-y">{items.map(p=><button key={p.slug} className="w-full text-left py-4 flex justify-between" onClick={()=>{setForm({...blank(),...p});setEditing(true);}}><span>{bl(p.name).en}</span><span>{p.status}</span></button>)}{!items.length&&<p>No profiles yet.</p>}</div>}
  </section>;
}
