import {useUnsavedChanges,confirmLeave} from '../../hooks/useUnsavedChanges';
import {useEffect,useState} from 'react';
import axios from 'axios';
import {API,auth,errorMessage} from '../../lib/cms';

const initial={path:'/',enabled:false,title:'We’re updating this page.',message:'This page is temporarily unavailable while we update its content. Please check back soon or contact Septa.',retry_after:3600};
export default function MaintenanceTab({token}) {
  const [data,setData]=useState({pages:[],settings:[]}),[form,setForm]=useState(initial),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
  const [dirty,setDirty]=useState(false);useUnsavedChanges(dirty);
  const change=next=>{setForm(next);setDirty(true);setNotice('');};
  const load=()=>axios.get(`${API}/admin/maintenance`,auth(token)).then(r=>{setData(r.data);return r.data;});
  useEffect(()=>{load().then(d=>setForm({...initial,...d.settings.find(item=>item.path==='/')})).catch(e=>setError(errorMessage(e)));},[token]); // eslint-disable-line react-hooks/exhaustive-deps
  const save=async e=>{e.preventDefault();if(form.enabled&&!window.confirm(`Temporarily close ${form.path} to visitors? Other pages and admin will stay available.`))return;setBusy(true);setError('');try{await axios.put(`${API}/admin/maintenance`,form,auth(token));await load();setDirty(false);setNotice(form.enabled?'Page placed in maintenance.':'Page reopened.');}catch(e){setError(errorMessage(e));}finally{setBusy(false);}};
  return <section className="bg-white p-6 space-y-6"><h2 className="font-sora text-2xl">Page maintenance</h2><p>Close one page while you prepare content. The public URL returns a temporary 503 response with a retry instruction. Admin stays accessible. Remember to reopen the page promptly.</p><p className="text-sm text-[#606060]">Maintenance is not a privacy setting: previously public files and data may remain accessible. Use drafts and publication permissions for content that must not be public.</p><form onSubmit={save} className="space-y-5"><label className="block">Page<select className="form-input" value={form.path} onChange={e=>{if(!confirmLeave())return;setDirty(false);setForm({...initial,path:e.target.value,...data.settings.find(item=>item.path===e.target.value)});setNotice('');}}>{data.pages.map(p=><option key={p.path} value={p.path}>{p.label} — {p.path}</option>)}</select></label><label className="flex gap-3"><input type="checkbox" checked={form.enabled} onChange={e=>change({...form,enabled:e.target.checked})}/>Temporarily close this page</label><label className="block">Visitor heading<input className="form-input" required maxLength={100} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="block">Visitor message<textarea className="form-input" rows={3} maxLength={500} value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/></label><p className="text-sm">Applies to this exact URL only; closing the Projects listing does not close individual projects.</p>{error&&<p role="alert" className="text-red-700">{error}</p>}{notice&&<p role="status">{notice}</p>}<div className="flex gap-5 flex-wrap"><button className="design-button" disabled={busy}>{busy?'Saving…':'Save availability'}</button><a href={`${form.path}?preview=true`} target="_blank" rel="noreferrer" className="design-text-link">Open authenticated preview ↗</a><a href={form.path} target="_blank" rel="noreferrer" className="design-text-link">View visitor page ↗</a></div></form><h3 className="text-xl">Currently closed</h3>{data.settings.filter(s=>s.enabled).map(s=><p key={s.path}>{s.path}</p>)}{!data.settings.some(s=>s.enabled)&&<p>All pages are open.</p>}</section>;
}
