import {useState} from 'react';

import {mediaRules,ratioName} from '../../lib/mediaRules';
export {validateMediaRatio,ratioName} from '../../lib/mediaRules';
const names=Object.fromEntries(Object.entries(mediaRules).map(([k,v])=>[k,v[1]]));
const brand=`You are editing source media for Septa Group, a Kerala-based architecture and construction company. Do not assume prior knowledge of the brand. Its website is editorial and architectural: carbon black #050505, warm off-white #F6F6F3, muted brass #C6A15B used sparingly, cool charcoal #606060, pale stone #ECECEA. Layouts have straight architectural lines, generous negative space, quiet typographic hierarchy, authentic Kerala context and real material textures. The desired photographic grade is natural, restrained and premium: neutral warm whites, truthful timber, controlled highlights, deep shadows with visible detail, slightly restrained saturation, no heavy orange/teal film filter, no fake HDR, no glossy CGI. A person remains recognisably the same person, and built work remains the actual building. Preserve structure, materials, proportions, original marks and credit information. Never invent credentials, logos, site details or project outcomes. If an image is a render, keep it visibly and clearly a render; never disguise it as a built project. Produce a polished, realistic high-resolution asset WITHOUT added text. Suggest a crop only if it can preserve essential details; otherwise tell me a different source photograph is needed. Return one image at the specified ratio and check the result against my original.`;
const tasks={
 social_image:'Create a 1.91:1 social sharing image (1200 × 628 pixels) from this approved photograph. Preserve the real subject and frame it clearly at thumbnail size; keep important details within the central 80 percent. Do not add text or fabricate project work.',
 page_image:'Prepare a 16:9 editorial section image from the supplied photograph. Preserve the real subject and architecture, correct camera tilt and exposure, and leave comfortable negative space. Do not add text.',
 portrait_image:'Create a 4:5 chest-up portrait for a professional collaborator or Septa team member. Preserve their identity and skin tone exactly; correct perspective, exposure, sharpness and background, with soft natural directional light and comfortable headroom. Do not replace clothing, glasses or facial features without permission. Keep eyes in the upper third, face within central safe area. This image is for a person, never a building.',
 card_image:'Create a 16:9 collaborator card from a photograph of the person’s actual work or studio. This is separate from the headshot. Frame the central 70% as the safe area, with a distinctive architectural focal point and room for a lower text overlay; avoid tiny subjects and invented context. Match the grading of other cards. Multiple selected images should have the same exposure and cropping discipline so a fade transition feels coherent.',
 logo_image:'Isolate the supplied original company logo onto a genuinely transparent 1:1 canvas. REMOVE the background completely, including any white rectangular box, paper, photographed surface or fake checkerboard. Preserve white elements that belong to the actual mark: do not erase them. Keep the exact symbol, lettering, colours, proportions and edge quality. Centre the mark with 10 percent transparent padding. Export a transparent PNG with a real alpha channel (1024 × 1024), not JPG. Do not add a white tile, shadow, mockup or replacement logo. Do not claim a bitmap is SVG; if a vector file is needed, request the original vector source. Check the result over both black and ivory backgrounds. If background and mark cannot be separated confidently, ask for the original logo file.',
 hero_image:'Create a 16:9 wide profile hero. Level verticals and find a strong central architectural subject, with unbusy darker space toward the lower left for white title text. Protect the subject for center crop on mobile. Keep the built space truthful.',
 gallery_images:'Prepare this one gallery item at 16:9 for a compact portfolio filmstrip. Preserve its project identity, label renders as renders separately, correct camera tilt and exposure, keep honest textures and ensure the subject is readable at thumbnail size. Match the restrained Septa grade consistently across gallery items.',
 video_poster:'Make a 16:9 static video cover from an approved frame or associated project photo. Create a clean focal point with center safe area and enough tonal separation for the website play button overlay. Do not add an artificial play icon or video title to the image; the website supplies those.',
 project_cover:'Make a 16:9 project cover from the actual project photo. Composition should show the architectural work clearly, with clean verticals, natural Kerala light, room for overlay text at the bottom and no fabricated site conditions.',
 project_gallery:'Make a 16:9 gallery photo of this specific project. Keep it documentary accurate, architecturally legible and harmonious with the other photographs from this same project. Retain photographer credit and relevant site details.',
 project_render:'Prepare the supplied architectural render at 16:9 with legible materials and balanced lighting. This must remain an architectural visualization and be labelled as such in the website caption. Never make it look like documentary evidence of a completed building.',
 public_plan:'This is an approved public drawing. Preserve EVERY dimension, label, line, north arrow and scale exactly. Do not redraw, interpret, beautify or invent technical information. Only straighten a scanned sheet and improve legibility. Fit the entire original sheet inside a 16:9 image using plain padding; never crop or stretch the drawing. A PDF preserves its original sheet ratio and can be uploaded as-is without using AI.',
 testimonial_cover:'Make a 16:9 testimonial cover from an approved photo of the relevant finished work or person. Keep an uncluttered central subject, realistic light and a quieter area for website text. Do not invent a person or imply they said words they did not say.',
 testimonial_portrait:'Prepare the client’s consented original portrait at 1:1; preserve facial identity, natural skin tone and headroom for the circular website crop. Do not create a fabricated person.',
 page_hero:'Create a 16:9 opening image for the Septa Group website, suitable for a black or ivory editorial split layout. Choose clear architectural subject, preserve accurate building and materials, leave controlled negative space for adjacent website copy. No text in the image.',
 virtual_tour_image:'Only process a REAL 360-degree equirectangular panorama into a 2:1 file. Preserve the entire 360-degree wrap seamlessly; do not crop, mirror, invent new rooms or pretend an ordinary flat photo is a navigable panorama.'
 ,page_video:'Prepare a 16:9 opening film. Follow a clear architectural story with calm camera movement, steady exposure and truthful spaces. Keep cuts unhurried and protect an appealing representative frame for its cover. Avoid stock footage implying it is Septa work.',
 partner_video:'Prepare a 16:9 partner profile film. Show the collaborator’s real work and accurately credit them; trim dead time, stabilise shots and match understated tonal treatment across clips. Do not add fabricated construction progress or unrelated projects.',
 project_video:'Prepare a 16:9 project film from authentic approved footage of this exact project. Maintain location and sequence truth, clean audio, steady restrained camera motion, no invented project claims and no added marketing copy embedded in the picture.'
};
export default function MediaGuide({field,index}){
 const [copied,setCopied]=useState(false),[copyError,setCopyError]=useState(false);
 const copy=async()=>{try{const prompt=`${brand}\n\nSPECIFIC OUTPUT FOR THIS FIELD (${names[field]||'original format'}): ${tasks[field]||tasks.page_hero}${index!=null?`\n\nThis is item ${index+1}. Keep the original project and its attribution distinct from other items.`:''}\n\nREQUIRED EXPORT: ${ratioName(field)}, ${mediaRules[field]?.[3]||'1920 × 1080'} pixels.\n\nUse ONLY the source media I attach with this prompt. If the photo cannot safely be adapted to this aspect ratio, explain why instead of inventing missing content.`;await navigator.clipboard.writeText(prompt);setCopied(true);setTimeout(()=>setCopied(false),2400);}catch{setCopyError(true);}};
 return <div className="media-guide" data-media-role={field}><span className="media-ratio-badge">Required: <strong>{ratioName(field)}</strong></span><span className="text-[#606060]">Export {mediaRules[field]?.[3]||'1920 × 1080'} · {field==='logo_image'?'transparent PNG':'JPG, PNG or WebP'}</span><button type="button" onClick={copy} className="underline underline-offset-4 font-semibold text-[#050505]">{copied?'Detailed prompt copied':'Copy complete AI prompt'}</button><span className="text-[#606060]">Attach the source file with the prompt. Verify before publishing.</span>{copyError&&<details open><summary>Copy manually (clipboard unavailable)</summary><textarea readOnly aria-label="AI editing prompt" value={`${brand}\n\n${tasks[field]||tasks.page_hero}\nRequired ratio: ${ratioName(field)}`}/></details>}</div>;
}
