import {ArrowUp,ArrowDown,Plus,Trash2} from 'lucide-react';
import {newId} from '../../lib/pageContent';
import {editableNavigation,footerGroupsFor} from '../../lib/navigation';
import {Field} from './Fields';
export default function NavigationSettings({settings,setSettings}){
 const brand=settings.brand||{},links=editableNavigation(settings),groups=footerGroupsFor(settings),appearance=settings.appearance||{};
 const setLinks=navigation=>setSettings({...settings,navigation,navigation_version:2});
 const edit=(i,patch)=>setLinks(links.map((l,n)=>i===n?{...l,...patch}:l));
 const move=(i,d)=>{const copy=[...links];[copy[i],copy[i+d]]=[copy[i+d],copy[i]];setLinks(copy);};
 const changeGroups=footer_groups=>setSettings({...settings,footer_groups});
 const appearanceChange=patch=>setSettings({...settings,appearance:{...appearance,...patch}});
 return <div className="space-y-8 bg-white border p-6">
 <div><h3 className="text-xl mb-5">Identity & main action</h3><div className="grid md:grid-cols-2 gap-5">{[['name','Brand name','SEPTA GROUP'],['logo_url','Logo image URL','/septa-logo.png'],['cta_label','Main button label','Discuss your project'],['cta_url','Main button destination','/contact']].map(([key,label,fallback])=><Field key={key} label={label}><input value={brand[key]??fallback} onChange={e=>setSettings({...settings,brand:{...brand,[key]:e.target.value}})}/></Field>)}</div></div>
 <div><h3 className="text-xl mb-4">Motion & surface effects</h3><div className="grid md:grid-cols-2 gap-5"><Field label="Motion"><select value={appearance.motion||'subtle'} onChange={e=>appearanceChange({motion:e.target.value})}><option value="off">Off</option><option value="subtle">Subtle</option><option value="expressive">Expressive</option></select></Field>{[['header_glass','Glass header'],['globe_animation','Animate globe'],['mobile_contact_bar','Mobile Call / WhatsApp bar']].map(([key,label])=><label key={key} className="flex gap-3 items-center"><input type="checkbox" checked={appearance[key]!==false} onChange={e=>appearanceChange({[key]:e.target.checked})}/>{label}</label>)}</div><p className="text-xs text-neutral-500 mt-3">Visitors’ reduced-motion preferences always take priority. Content stays visible when motion is off.</p></div>
 <div><h3 className="text-xl mb-4">Footer groups</h3><div className="space-y-3">{groups.map((group,i)=><div key={group.id} className="border p-3 flex flex-wrap items-center gap-3"><input aria-label={`Footer group ${i+1} name`} className="form-input flex-1" value={group.label} onChange={e=>changeGroups(groups.map((g,n)=>n===i?{...g,label:e.target.value}:g))}/><label className="text-xs"><input type="checkbox" checked={!!group.show_address} onChange={e=>changeGroups(groups.map((g,n)=>n===i?{...g,show_address:e.target.checked}:g))}/> Show office address</label><button disabled={!i} aria-label={`Move ${group.label} group up`} onClick={()=>{const copy=[...groups];[copy[i-1],copy[i]]=[copy[i],copy[i-1]];changeGroups(copy);}}><ArrowUp size={16}/></button><button aria-label={`Remove ${group.label} group`} onClick={()=>changeGroups(groups.filter(g=>g.id!==group.id))}><Trash2 size={16}/></button></div>)}</div><button className="border p-3 mt-3 text-sm" onClick={()=>changeGroups([...groups,{id:newId(),label:'New group'}])}>Add footer group</button></div>
 <div><h3 className="text-xl mb-3">Navigation links</h3><p className="text-sm text-neutral-500 mb-5">Choose desktop, burger-menu and footer visibility independently. Contact links read from Contact Info automatically.</p><div className="space-y-4">{links.map((l,i)=><div className="border p-4 space-y-4" key={l.key}><div className="grid md:grid-cols-2 gap-4"><Field label="Link label"><input value={l.label} onChange={e=>edit(i,{label:e.target.value})}/></Field><Field label="Destination source"><select value={l.source||'custom'} onChange={e=>edit(i,{source:e.target.value==='custom'?'':e.target.value})}><option value="custom">Custom page / URL</option>{['call','whatsapp','email','map','facebook','instagram'].map(source=><option key={source} value={source}>{source} from Contact Info</option>)}</select></Field>{!l.source&&<Field label="Destination"><input value={l.url} onChange={e=>edit(i,{url:e.target.value})}/></Field>}<Field label="Footer group"><select value={l.footer_group||'explore'} onChange={e=>edit(i,{footer_group:e.target.value})}>{!groups.some(g=>g.id===l.footer_group)&&<option value={l.footer_group||'explore'}>Choose a group</option>}{groups.map(g=><option key={g.id} value={g.id}>{g.label}</option>)}</select></Field><Field label="Burger-menu group"><select value={l.mobile_group||'main'} onChange={e=>edit(i,{mobile_group:e.target.value})}><option value="main">Main links</option><option value="secondary">More about Septa</option></select></Field></div><div className="flex flex-wrap items-center gap-5 text-sm">{[['header','Desktop header'],['mobile','Burger menu'],['footer','Footer']].map(([key,label])=><label key={key}><input type="checkbox" checked={!!l[key]} onChange={e=>edit(i,{[key]:e.target.checked})}/> {label}</label>)}<button aria-label={`Move ${l.label} up`} disabled={!i} onClick={()=>move(i,-1)}><ArrowUp size={16}/></button><button aria-label={`Move ${l.label} down`} disabled={i===links.length-1} onClick={()=>move(i,1)}><ArrowDown size={16}/></button><button aria-label={`Remove ${l.label}`} onClick={()=>setLinks(links.filter((_,n)=>n!==i))}><Trash2 size={16}/></button></div></div>)}</div><button onClick={()=>setLinks([...links,{key:newId(),label:'New link',url:'/',header:false,mobile:true,footer:true,footer_group:groups[0]?.id||'explore'}])} className="flex items-center gap-2 border p-3 mt-5 text-sm"><Plus size={16}/>Add link</button></div>
 </div>;
}
