import {ArrowUp,ArrowDown,Plus,Trash2} from 'lucide-react';
import {defaultNavigation,newId} from '../../lib/pageContent';
import {Field} from './Fields';
export default function NavigationSettings({settings,setSettings}){
 const brand=settings.brand||{};
 const links=settings.navigation||defaultNavigation.map(l=>({...l,header:l.header&&settings.nav_visibility?.[l.key]!==false,footer:l.footer&&settings.nav_visibility?.[l.key]!==false}));
 const setLinks=navigation=>setSettings({...settings,navigation});
 const edit=(i,patch)=>setLinks(links.map((l,n)=>i===n?{...l,...patch}:l));
 const move=(i,d)=>{const copy=[...links];[copy[i],copy[i+d]]=[copy[i+d],copy[i]];setLinks(copy);};
 return <div className="space-y-8 bg-white border p-6"><div><h3 className="text-xl mb-5">Identity & main action</h3><div className="grid md:grid-cols-2 gap-5">{[['name','Brand name','SEPTA GROUP'],['logo_url','Logo image URL','/septa-logo.png'],['cta_label','Main button label','Discuss your project'],['cta_url','Main button destination','/contact']].map(([key,label,fallback])=><Field key={key} label={label}><input value={brand[key]??fallback} onChange={e=>setSettings({...settings,brand:{...brand,[key]:e.target.value}})}/></Field>)}</div></div><div><h3 className="text-xl mb-3">Navigation</h3><p className="text-sm text-neutral-500 mb-5">Choose what appears in the header and footer. Hiding a navigation link does not unpublish its destination.</p><div className="space-y-4">{links.map((l,i)=><div className="border p-4 space-y-4" key={l.key}><div className="grid md:grid-cols-2 gap-4"><Field label="Link label"><input value={l.label} onChange={e=>edit(i,{label:e.target.value})}/></Field><Field label="Destination"><input value={l.url} onChange={e=>edit(i,{url:e.target.value})}/></Field></div><div className="flex flex-wrap items-center gap-5 text-sm"><label><input type="checkbox" checked={l.header} onChange={e=>edit(i,{header:e.target.checked})}/> Header</label><label><input type="checkbox" checked={l.footer} onChange={e=>edit(i,{footer:e.target.checked})}/> Footer</label><button aria-label={`Move ${l.label} up`} disabled={i===0} onClick={()=>move(i,-1)}><ArrowUp size={16}/></button><button aria-label={`Move ${l.label} down`} disabled={i===links.length-1} onClick={()=>move(i,1)}><ArrowDown size={16}/></button><button aria-label={`Remove ${l.label}`} onClick={()=>setLinks(links.filter((_,n)=>n!==i))}><Trash2 size={16}/></button></div></div>)}</div><button onClick={()=>setLinks([...links,{key:newId(),label:'New link',url:'/',header:false,footer:true}])} className="flex items-center gap-2 border p-3 mt-5 text-sm"><Plus size={16}/>Add link</button></div></div>;
}
