import {validateRecordImages} from '../../lib/mediaRules';
import {useState} from 'react';
import axios from 'axios';
import {useAdminTestimonials,useProjects,getText,uploadFile} from '../../hooks/useApi';
import {API,auth,errorMessage,bl} from '../../lib/cms';
import {Field,BilingualField,PublicationFields} from './Fields';
import MediaGuide,{validateMediaRatio} from './MediaGuide';
export default function TestimonialsTab({token}){
 const {testimonials,loading,setTestimonials}=useAdminTestimonials(token),{data:projects}=useProjects(),[form,setForm]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const save=async e=>{e.preventDefault();setBusy(true);setError('');try{await validateRecordImages(form,testimonials.find(t=>t.id===form.id),'testimonial');const {data}=await axios[form.id?'put':'post'](`${API}/testimonials${form.id?'/'+form.id:''}`,form,auth(token));setTestimonials(list=>form.id?list.map(t=>t.id===form.id?form:t):[...list,{...form,id:data.id}]);setForm(null);}catch(e){setError(errorMessage(e));}finally{setBusy(false);}};
 const upload=async(e,key)=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);setError('');try{const issue=await validateMediaRatio(file,key==='cover_image'?'testimonial_cover':'testimonial_portrait');if(issue){setError(issue);return;}const result=await uploadFile(token,file,key==='cover_image'?'testimonial_cover':'testimonial_portrait');setForm(f=>({...f,[key]:result.url}));}catch(e){setError(errorMessage(e));}finally{setBusy(false);}};
 return <section className="bg-white p-6 space-y-5"><div className="flex justify-between"><h2 className="text-xl">Testimonials</h2><button onClick={()=>setForm({content:bl(),client_name:'',client_role:'',project_type:'',project_ref:'',completed_project:false,profile_image:'',cover_image:'',status:'draft',publication_reviewed:false})}>Add testimonial</button></div><p>Use the client’s approved words and confirm permission before publication.</p>{error&&<p role="alert">{error}</p>}{form?<form onSubmit={save} className="space-y-5">{['client_name','client_role'].map(k=><Field key={k} label={k.replaceAll('_',' ')}><input required={k==='client_name'} value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})}/></Field>)}<BilingualField label="Client’s words" value={form.content} onChange={content=>setForm({...form,content})}/><div className="grid md:grid-cols-2 gap-6">{[['profile_image','Client profile photo'],['cover_image','Testimonial cover image']].map(([key,label])=><div key={key}><MediaGuide field={key==='cover_image'?'testimonial_cover':'testimonial_portrait'}/><Field label={label}><input value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})}/></Field><input aria-label={`Upload ${label}`} type="file" accept="image/jpeg,image/png,image/webp,image/gif" disabled={busy} onChange={e=>upload(e,key)}/>{form[key]&&<img className="max-h-40 mt-3" src={form[key]} alt={label}/>}</div>)}</div><label className="flex gap-3"><input type="checkbox" checked={!!form.completed_project} onChange={e=>setForm({...form,completed_project:e.target.checked,project_ref:''})}/>This testimonial is about a completed project</label><Field label="Related project (optional)"><select value={form.project_ref||''} onChange={e=>setForm({...form,project_ref:e.target.value})}><option value="">No project link</option>{projects.filter(p=>!form.completed_project||p.project_status==='Completed').map(p=><option key={p.slug} value={p.slug}>{getText(p.title)}</option>)}</select></Field><p className="text-sm">Only published projects can be linked. Linked testimonials also appear on that project’s page.</p><PublicationFields value={form} onChange={v=>setForm({...form,...v})}/><button disabled={busy} className="bg-black text-white p-3 mr-5">Save</button><button type="button" onClick={()=>setForm(null)}>Cancel</button></form>:loading?<p>Loading…</p>:testimonials.map(t=><button key={t.id} onClick={()=>setForm({...t,content:bl(t.content)})} className="block w-full text-left border p-4"><p>{getText(t.content)}</p><p className="text-sm mt-2">{t.client_name} · {t.status||'Unreviewed'}</p></button>)}</section>;
}
