import {useEffect,useState} from 'react';
import axios from 'axios';
import {API,auth,errorMessage} from '../../lib/cms';
import {Field} from './Fields';
export default function UsersTab({token,admin,authMode='password'}){
 const [users,setUsers]=useState([]),[form,setForm]=useState({email:'',password:'',role:'editor'}),[error,setError]=useState(''),[msg,setMsg]=useState('');
 const refresh=()=>axios.get(`${API}/admin/users`,auth(token)).then(r=>setUsers(r.data)).catch(e=>setError(errorMessage(e)));
 useEffect(()=>{refresh();},[token]); // eslint-disable-line react-hooks/exhaustive-deps
 const create=async e=>{e.preventDefault();setError('');setMsg('');try{await axios.post(`${API}/admin/users`,authMode==='google'?{email:form.email,role:form.role}:form,auth(token));setForm({email:'',password:'',role:'editor'});setMsg('Account created');refresh();}catch(e){setError(errorMessage(e));}};
 const update=async(u,change)=>{try{await axios.patch(`${API}/admin/users/${u.id}`,change,auth(token));refresh();}catch(e){setError(errorMessage(e));}};
 return <section className="bg-white p-6 space-y-7"><h2 className="text-xl">Admin accounts</h2><p className="text-sm text-neutral-600">Owner accounts control users and publishing. Editors can prepare records; publishers can approve content. Previous sessions are revoked when access changes.</p>{error&&<p role="alert" className="text-red-700">{error}</p>}{msg&&<p className="text-green-700">{msg}</p>}<div className="divide-y">{users.map(u=><div key={u.id} className="py-4 flex flex-wrap items-center justify-between gap-4"><div><strong>{u.email}</strong><p className="text-xs text-neutral-500">{u.disabled?'Disabled':'Active'}</p></div><div className="flex gap-3 items-center"><select disabled={u.id===admin?.id} value={u.role} onChange={e=>update(u,{role:e.target.value,disabled:!!u.disabled})}><option>editor</option><option>publisher</option><option>owner</option></select><button disabled={u.id===admin?.id} onClick={()=>update(u,{role:u.role,disabled:!u.disabled})}>{u.disabled?'Enable':'Disable'}</button></div></div>)}</div><form onSubmit={create} className="border-t pt-6 space-y-4"><h3 className="text-lg">Add account</h3><Field label="Email"><input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Field>{authMode!=='google'&&<Field label="Temporary password (12+ characters)"><input required minLength={12} type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></Field>}<Field label="Role"><select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option>editor</option><option>publisher</option><option>owner</option></select></Field><button className="bg-black text-white px-4 py-3">Create account</button></form></section>;
}
