import { ManagedIntro } from '../components/PageSections';
import {Link,useParams,useSearchParams} from 'react-router-dom';
import {useApiData,getText} from '../hooks/useApi';
import {safeHref} from '../lib/pageContent';
export default function LeadersPage(){
 const {slug}=useParams(),[params]=useSearchParams();
 const {data,loading,error}=useApiData(slug?`/leaders/${slug}${params.get('preview')==='true'?'?preview=true':''}`:'/leaders',slug?null:[]);
 const {data:projects}=useApiData(slug?`/credits/leader/${slug}/projects`:'/projects',[]);
 if(loading)return <div className="pt-32 px-6" role="status">Loading project leaders…</div>;
 if(error||(slug&&!loading&&!data))return <div className="pt-32 px-6"><h1>Profile unavailable</h1><Link to="/project-leaders">All project leaders</Link></div>;
 if(slug)return <div className="pt-28 pb-24 max-w-6xl mx-auto px-6"><Link to="/project-leaders" className="design-text-link">← All project leaders</Link><div className="grid md:grid-cols-[minmax(230px,2fr)_3fr] gap-8 md:gap-16 mt-10 items-start">{safeHref(data.photo)&&<img src={safeHref(data.photo)} alt={getText(data.name)} className="w-full aspect-[4/5] object-cover"/>}<div><p className="design-eyebrow">Septa Group / Project leadership</p><h1 className="text-4xl md:text-6xl mt-4 mb-5 font-sora">{getText(data.name)}</h1><p className="text-xl md:text-2xl font-medium border-l-4 border-[#C6A15B] pl-5">{getText(data.title)}</p><p className="whitespace-pre-line leading-relaxed my-9 max-w-prose text-[#606060]">{getText(data.bio)}</p>{(data.highlights||[]).some(item=>item.visible!==false&&item.value&&item.label)&&<div className="leader-highlights">{data.highlights.filter(item=>item.visible!==false&&item.value&&item.label).map((item,i)=><div key={i}><strong>{item.value}</strong><span>{item.label}</span></div>)}</div>}<div className="leader-detail-grid">{data.expertise?.filter(Boolean).length>0&&<section className="leader-expertise"><h2>01 / Expertise</h2><ol>{data.expertise.filter(Boolean).map((v,i)=><li key={v}><span>{String(i+1).padStart(2,'0')}</span>{v}</li>)}</ol></section>}{data.qualifications?.filter(Boolean).length>0&&<section className="leader-qualifications"><h2>02 / Qualifications</h2><ul>{data.qualifications.filter(Boolean).map(v=><li key={v}>{v}</li>)}</ul></section>}</div><Link className="inline-block bg-black text-white px-6 py-4 mt-8" to={`/contact?leader=${slug}&enquiry_type=introduction`}>Discuss a project with {getText(data.name)} ↗</Link></div></div><h2 className="text-3xl mt-20 mb-8">Credited projects</h2><div className="grid md:grid-cols-2 gap-6">{projects.map(p=><Link key={p.slug} to={`/projects/${p.slug}`} className="border p-6 hover:border-[#C6A15B] transition-colors">{p.image&&<img src={safeHref(p.image)} alt="" loading="lazy" className="aspect-video w-full object-cover mb-4"/>}<h3 className="text-xl font-semibold">{getText(p.title)}</h3><p>{p.location}</p><p className="mt-2">{p.credits?.filter(c=>c.entity_type==='leader'&&c.entity_slug===slug).map(c=>c.role).join(', ')}</p></Link>)}</div>{!projects.length&&<p>Project credits will appear here when reviewed and published.</p>}</div>;
 const ordered=[...data].sort((a,b)=>(a.hierarchy_rank??100)-(b.hierarchy_rank??100)||getText(a.name).localeCompare(getText(b.name)));
 return <div className="pt-16 pb-24"><ManagedIntro pageId="leaders"/><div className="max-w-6xl mx-auto px-6 mt-14"><p className="design-eyebrow">Septa Group / Leadership</p><h2 className="text-3xl md:text-4xl mb-8">The people responsible for the work.</h2><div className="grid sm:grid-cols-2 md:grid-cols-3 gap-8">{ordered.map(p=><Link key={p.slug} to={`/project-leaders/${p.slug}`} className="group border-b pb-6">{safeHref(p.photo)&&<img src={safeHref(p.photo)} alt={getText(p.name)} loading="lazy" className="aspect-[4/5] object-cover w-full mb-5"/>}<h3 className="text-2xl font-semibold group-hover:underline">{getText(p.name)}</h3><p className="mt-1 text-[#606060]">{getText(p.title)}</p></Link>)}</div>{!data.length&&<p>Leader profiles are being prepared for publication. <Link to="/contact" className="underline">Contact Septa to discuss your project.</Link></p>}</div></div>;
}
