import ResponsiveImage from '../components/ResponsiveImage';
import ContentError from '../components/ContentError';
import { Link, useParams, useSearchParams } from 'react-router-dom';
import { useApiData, getText } from '../hooks/useApi';

export default function SearchLandingPage({kind}) {
  const {slug} = useParams();
  const [params]=useSearchParams(),preview=params.get('preview')==='true';
  const {data: page, loading, error,statusCode,retry} = useApiData(`/search-pages/${kind}/${slug}${preview?'?preview=true':''}`, null);
  if(!page)return loading?<div className="design-container pt-36 pb-24" role="status">Loading page…</div>:<ContentError label="Page" notFound={statusCode===404} retry={retry} back="/services"/>;
  return <article className="bg-[#F6F6F3] text-[#050505]">{preview&&<div className="design-preview-banner">Saved draft preview · Not public <Link to="/admin">Back to admin</Link></div>}<header className="pt-36 pb-20 px-6 bg-[#101010] text-white"><div className="max-w-6xl mx-auto"><p className="text-xs uppercase tracking-[.22em] text-white/60 mb-8">Septa Group / {kind === 'service' ? 'Capabilities' : 'Places we work'}</p><h1 className="font-sora text-4xl md:text-6xl max-w-4xl leading-tight">{page.title}</h1><p className="text-lg md:text-xl text-white/75 mt-8 max-w-3xl leading-relaxed">{page.introduction}</p></div></header><div className="max-w-6xl mx-auto px-6 py-20 grid md:grid-cols-[minmax(0,2fr)_minmax(14rem,1fr)] gap-14"><div className="space-y-7 text-base leading-relaxed text-black/75">{page.image&&<ResponsiveImage src={page.image} alt={page.image_alt||''} className="aspect-video w-full object-cover" loading="lazy"/>}{page.paragraphs?.map((paragraph,index) => paragraph&&<section key={index}>{page.paragraph_headings?.[index]&&<h2 className="font-sora text-2xl mb-4 text-black">{page.paragraph_headings[index]}</h2>}<p>{paragraph}</p></section>)}</div><aside className="md:border-l border-black/15 md:pl-8"><h2 className="font-sora text-xl mb-6">Documented work</h2><div className="space-y-6">{page.projects?.map(project => <Link key={project.slug} to={`/projects/${project.slug}`} className="block border-b border-black/15 pb-5 hover:opacity-65"><span className="font-sora text-lg block">{getText(project.title)}</span><span className="text-sm text-black/55">{project.location}</span></Link>)}</div></aside></div><div className="max-w-6xl mx-auto px-6 pb-24"><Link to="/contact" className="inline-block bg-[#050505] text-white px-7 py-4 text-sm uppercase tracking-wider hover:bg-[#333]">Discuss a project with Septa ↗</Link></div></article>;
}
